import{a as m,S,i}from"./assets/vendor-CesYmgD5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const P="57443063-5f386e005ea466bbe0c4b67c4";m.defaults.baseURL="https://pixabay.com/api/";async function f(s,t){return(await m.get("",{params:{key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),R=new S(".gallery a",{captionsData:"alt",captionDelay:250});function b(s){const t=s.map(({webformatURL:o,largeImageURL:l,tags:e,likes:r,views:n,comments:q,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${o}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${r}</span></p>
          <p class="info-item"><b>Views</b><span>${n}</span></p>
          <p class="info-item"><b>Comments</b><span>${q}</span></p>
          <p class="info-item"><b>Downloads</b><span>${v}</span></p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){g.innerHTML=""}function L(){h.classList.remove("is-hidden")}function p(){h.classList.add("is-hidden")}function w(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}const B=document.querySelector(".form"),E=document.querySelector(".load-more");let d="",a=1,u=0;c();p();B.addEventListener("submit",async s=>{s.preventDefault();const t=s.currentTarget.elements.searchQuery.value.trim();if(!t){i.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}d=t,a=1,$(),c(),L();try{const o=await f(d,a);if(u=o.totalHits,o.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(o.hits),a*15<u?w():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}});E.addEventListener("click",async()=>{a+=1,c(),L();try{const s=await f(d,a);b(s.hits);const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}a*15>=u?(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch{i.error({title:"Error",message:"Something went wrong while fetching more images.",position:"topRight"})}finally{p()}});
//# sourceMappingURL=index.js.map
